apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rfaf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rfaf
    app.kubernetes.io/part-of: tkrw-pr714-0075-0009-app
  name: devfile-sample-rfaf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rfaf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rfaf
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0009-tenant/tkrw-pr714-0075-0009-app/devfile-sample-rfaf@sha256:0c09e047ca8a02c574eb88712d6af0ef5e2c5d133011c18982c47de28ffc4699
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
